### ISSUE TITLE
Dependency changing to `nil` is not detected

### ISSUE THREAD

**Issue by foxydevloper** [Kampfkarren/roact-hooks#31]
For `useEffect`, when a dependency changes to `nil`, it doesn't re-run the function.
In this example, if the `visible` prop to `UserComponent` becomes `false`, it will not cancel the promise, even though the user id dependency changed to `nil`
```lua
local function useUsername(hooks, userId)
    local username, setUsername = hooks.useState(nil)
    hooks.useEffect(function()
        setUsername(nil)
        if userId then
            local promise = getNameFromId(userId):andThen(setUsername)
            return function()
                promise:cancel()
            end
        end
    end, {userId})
    return username
end

local function UserComponent(props, hooks)
    local username = useUsername(hooks, if props.visible then props.userId else nil)
    -- render user related stuff with username
end
```
I could work around this by passing `visible` as a dependency, but it makes the hook less reusable. It should detect that the dependency changed to `nil` and re-run the effect.

**Comment by Kampfkarren** [comment]
https://github.com/Kampfkarren/roact-hooks/blob/9a7c9bd096a8d3d8196bcc4b882b29f342f1e114/src/init.lua#L85-90

These need to check for length of the tables too--by counting number of times pairs runs.
