### ISSUE TITLE
Hooks.new does not create an element with correct Props type 

### ISSUE THREAD

**Issue by andrewdkim** [Kampfkarren/roact-hooks#37]
I noticed that few days ago, typings for some of the functions have been included (Thanks for doing that!), and I attempted to use the latest version in my application. However, I noticed that when creating components using Hooks.new(Roact)(Component), the result resolves to a type "any" instead of the prop type of the component. 

Here's the sample code to illustrate the problem (I use Luau LSP + VSCode):

![Screen Shot 2022-08-09 at 12 41 28 AM](https://user-images.githubusercontent.com/46148447/183566461-3f29fb03-6ab2-45de-b3a7-e41f3483f7ca.png)

If I hover over the variable "MyCustomButton", I get a type "any":

![Screen Shot 2022-08-09 at 12 42 26 AM](https://user-images.githubusercontent.com/46148447/183566606-18494e8f-7bab-40f2-85df-91e312f7cce3.png)

This issue is crucial because when I eventually call Roact.createElement, Roact would not recognize the typing of the component, so LSP does not show component's prop suggestions:

![Screen Shot 2022-08-09 at 12 41 13 AM](https://user-images.githubusercontent.com/46148447/183566403-37219e9b-c7b2-42ff-bd6b-6500a2de021a.png)

Am I doing something wrong here?

**Comment by Kampfkarren** [comment]
CC @JohnnyMorganz

**Comment by JohnnyMorganz** [comment]
Nothing wrong here, it's just a current limitation of the types. There are a few things necessary to make this work:

1) We need a "RoactComponent<Props>" type that Roact understands and we can return
2) Roact needs to take in that type and use the Props to provide autocomplete for the props table.

Unfortunately, for the time being you won't get autocomplete for createElement. You should get it inside the functional component though for props and hooks

**Comment by andrewdkim** [comment]
Ah gotcha that's a bummer. Thanks for the prompt reply - and thanks again for the wonderful library!
